const CONFIG = {
  APPS_SCRIPT_URL: "https://script.google.com/macros/s/AKfycbwFrqtBF1ayf4n4S0mQAIVZss8uJMnJS8yQKrfLgI2XAF_JJ9NW5eSW1Kzi0fo4wd0WmA/exec",
  HUBSPOT_TOKEN: "FYLL_INN_PRIVATE_APP_TOKEN_HER",
  HUBSPOT_PORTAL_ID: "FYLL_INN_PORTAL_ID_HER"
};
