const CONFIG = {
      APPS_SCRIPT_URL: "https://script.google.com/macros/s/AKfycbx9cHwVDaPl4qwm7zhqPp42WGEx06YozyKXhWZ2Um9Yv27VJHjHtyfJH2XJTxFoCZay/exec",
  HUBSPOT_TOKEN: "FYLL_INN_PRIVATE_APP_TOKEN_HER",
  HUBSPOT_PORTAL_ID: "FYLL_INN_PORTAL_ID_HER"
};
